name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pythontests:
    timeout-minutes: 10
    strategy:
      matrix:
        container:
          - ubuntu:20.04
          - ubuntu:22.04
          - ubuntu:22.10
          - ubuntu:23.04
          - debian:unstable
      fail-fast: false

    runs-on: ubuntu-22.04
    container: ${{ matrix.container }}
    steps:
      - name: Install basic deps
        run: |
          apt-get update -y
          apt-get install -y \
            git \
            make \
            python3 \
            python3-pip \
            python3-venv \

      - uses: actions/checkout@v2

      - name: Run python tests
        run: |
          make pythontests

  verilator:
    timeout-minutes: 40
    runs-on: ubuntu-22.04
    container: verilator/verilator:latest

    steps:
      - uses: actions/checkout@v2

      - name: Run verilator tests
        run: |
          apt update
          apt-get install -y python3-venv
          make verilator

  formal:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    container: hdlc/yosys:latest

    steps:
      - uses: actions/checkout@v2

      - name: Run formal tests
        run: |
          apt update
          apt-get install -y python3-venv
          make formal
